
package vista;

import Logica.Mesa;
import Logica.Pedido;
import Logica.Producto;
import controlador.ControladorMesas;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class DialogNuevoPedido extends javax.swing.JDialog {

    private Mesa mesaSeleccionada = null;
    private ControladorMesas controladorPedidos;

    public DialogNuevoPedido(java.awt.Frame parent, boolean modal, Mesa mesa, ControladorMesas controlador) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        listarProductos(controlador.getProductos());
        controladorPedidos = controlador;
        mesaSeleccionada = mesa;
        lbl_tituloPedido.setText("Agregar pedido al servicio de la mesa " + mesa.getNumero());
        listarPedidos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Pedido = new javax.swing.JPanel();
        btn_AgregarPedido = new javax.swing.JButton();
        int_Cantidad = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        txt_Descripcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmb_Productos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lbl_tituloPedido = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lst_Pedidos = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_AgregarPedido.setText("Agregar pedido");
        btn_AgregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarPedidoActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad");

        jLabel2.setText("Descripción");

        jLabel1.setText("Productos");

        lbl_tituloPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_tituloPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tituloPedido.setText("Agregar pedido al servicio");

        jLabel4.setText("Nombre Producto - Cantidad - Descripción - Procesado");

        Lst_Pedidos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "No se encuentran pedidos" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(Lst_Pedidos);

        javax.swing.GroupLayout pnl_PedidoLayout = new javax.swing.GroupLayout(pnl_Pedido);
        pnl_Pedido.setLayout(pnl_PedidoLayout);
        pnl_PedidoLayout.setHorizontalGroup(
            pnl_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(pnl_PedidoLayout.createSequentialGroup()
                        .addGroup(pnl_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(cmb_Productos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Descripcion)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(int_Cantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_AgregarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_tituloPedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnl_PedidoLayout.setVerticalGroup(
            pnl_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PedidoLayout.createSequentialGroup()
                .addComponent(lbl_tituloPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(pnl_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(int_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_AgregarPedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Pedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AgregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarPedidoActionPerformed
        Producto p = controladorPedidos.getProductos().get(cmb_Productos.getSelectedIndex());
        String descripcion = txt_Descripcion.getText();
        int cantidad = (int) int_Cantidad.getValue();
        agregarPedido(mesaSeleccionada, p, descripcion, cantidad);
    }//GEN-LAST:event_btn_AgregarPedidoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList Lst_Pedidos;
    private javax.swing.JButton btn_AgregarPedido;
    private javax.swing.JComboBox<String> cmb_Productos;
    private javax.swing.JSpinner int_Cantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_tituloPedido;
    private javax.swing.JPanel pnl_Pedido;
    private javax.swing.JTextField txt_Descripcion;
    // End of variables declaration//GEN-END:variables

    public void listarProductos(ArrayList<Producto> productos) {
        for(Producto producto : productos){
            cmb_Productos.addItem(producto.getNombre());
        }
    }
    
    public void listarPedidos() {
        ArrayList<String> listado = new ArrayList();
        for (Pedido p : mesaSeleccionada.getServicio().getPedidos()) {
            listado.add(p.getProducto().getNombre() + " - " + p.getCantidad()
                        + " - " + p.getDescripcion() + " - " + p.Procesado());
        }
        Lst_Pedidos.setListData(listado.toArray());
    }
    
    public void agregarPedido(Mesa m, Producto p, String descripcion, int cantidad) {
        try {
            controladorPedidos.AgregarPedido(m, p, descripcion, cantidad);
            JOptionPane.showMessageDialog(null, "Se ha agregado el pedido");
            listarPedidos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
    }

}
