/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import Logica.Gestor;
import Logica.Sesion;
import Logica.UnidadProcesadora;
import controlador.ControladorUnidadesProcesadoras;
import controlador.IvistaUnidadesProcesadoras;
import java.util.ArrayList;

/**
 *
 * @author facu2
 */
public class VistaUnidadesProcesadoras extends javax.swing.JDialog implements IvistaUnidadesProcesadoras{

    ControladorUnidadesProcesadoras controlador;
    /**
     * Creates new form VistaUnidadesProcesadoras
     */
    public VistaUnidadesProcesadoras(java.awt.Frame parent, boolean modal, Sesion s){
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.controlador = new ControladorUnidadesProcesadoras(this, s);
        controlador.listarUnidades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmb_Unidades = new javax.swing.JComboBox<>();
        btn_Seleccionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        cmb_Unidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_UnidadesActionPerformed(evt);
            }
        });

        btn_Seleccionar.setText("Seleccionar");
        btn_Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SeleccionarActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccionar Unidad Procesadora:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmb_Unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Seleccionar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_Unidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Seleccionar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SeleccionarActionPerformed
        mostrarMonitor();
    }//GEN-LAST:event_btn_SeleccionarActionPerformed

    private void cmb_UnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_UnidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_UnidadesActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        logout();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Seleccionar;
    private javax.swing.JComboBox<String> cmb_Unidades;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarUnidades(ArrayList<UnidadProcesadora> unidades) {
        for(UnidadProcesadora u : unidades){
            cmb_Unidades.addItem(u.getNombre());
        }
    }
    
    public void mostrarMonitor(){
        Gestor g = controlador.getGestor();
        UnidadProcesadora u = controlador.getUnidades().get(cmb_Unidades.getSelectedIndex());
        new VistaMonitorPedidos(null, false, g, u).setVisible(true);
    }

    private void logout() {
        controlador.logout();
    }
}
