/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import Logica.Fachada;
import Logica.Gestor;
import Logica.Pedido;
import Logica.Sesion;
import Logica.UnidadProcesadora;
import controlador.ControladorMonitorPedidos;
import java.util.ArrayList;
import controlador.iVistaMonitorPedidos;

/**
 *
 * @author facundo.lopez
 */
public class VistaGestores extends javax.swing.JDialog implements iVistaMonitorPedidos{
    
    private ControladorMonitorPedidos controlador;

    /**
     * Creates new form VistaMonitorPedidos
     */
    public VistaGestores(java.awt.Frame parent, boolean modal, Sesion sesion) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.controlador = new ControladorMonitorPedidos(sesion, this);
        controlador.listarUnidades();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_PedidosUnidad = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_PedidosGestor = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btn_Procesar = new javax.swing.JButton();
        btn_Finalizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmb_Unidades = new javax.swing.JComboBox<>();
        btn_SeleccionarUnidad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pedidos de la Unidad");

        jScrollPane1.setViewportView(lst_PedidosUnidad);

        jScrollPane2.setViewportView(lst_PedidosGestor);

        jLabel2.setText("Pedidos del Gestor");

        btn_Procesar.setText("Procesar");

        btn_Finalizar.setText("Finalizar");
        btn_Finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FinalizarActionPerformed(evt);
            }
        });

        jLabel3.setText("Unidad Procesadora:");

        btn_SeleccionarUnidad.setText("Seleccionar");
        btn_SeleccionarUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SeleccionarUnidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmb_Unidades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_SeleccionarUnidad))
                        .addComponent(jLabel1))
                    .addComponent(btn_Procesar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Finalizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmb_Unidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SeleccionarUnidad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Procesar)
                    .addComponent(btn_Finalizar))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_FinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FinalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_FinalizarActionPerformed

    private void btn_SeleccionarUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SeleccionarUnidadActionPerformed
        UnidadProcesadora u = controlador.getUnidades().get(cmb_Unidades.getSelectedIndex());
        controlador.seleccionarUnidad(u);
        controlador.mostrarTitulo();
    }//GEN-LAST:event_btn_SeleccionarUnidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Finalizar;
    private javax.swing.JButton btn_Procesar;
    private javax.swing.JButton btn_SeleccionarUnidad;
    private javax.swing.JComboBox<String> cmb_Unidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lst_PedidosGestor;
    private javax.swing.JList lst_PedidosUnidad;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarPedidosUnidad(ArrayList<Pedido> pedidos) {
        
        ArrayList<String> listado = new ArrayList();
        for (Pedido p : pedidos) {
            listado.add(p.getProducto().getNombre() + " - " + p.getCantidad()
                        + " - " + p.getProducto().getPrecioUnitario() + " - " + 
                        (p.getProducto().getPrecioUnitario() * p.getCantidad()));
        }
        
        lst_PedidosUnidad.setListData(listado.toArray());
    }

    @Override
    public void mostrarPedidosGestor(ArrayList<Pedido> p) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mostrarTitulo(String titulo) {
        this.setTitle(titulo);
    }

    @Override
    public void listarUnidades(ArrayList<UnidadProcesadora> unidades) {
        for(UnidadProcesadora u : unidades){
            cmb_Unidades.addItem(u.getNombre());
        }
    }
}
